#!/bin/bash

# BFS
docker run --rm --volume $(pwd):$(pwd) -w $(pwd) cpcoh build/GCN3_X86/gem5.opt --debug-flags=GlobalScheduler,CPCoh,GPUDisp --debug-file=run_cpcoh.log --outdir=results_cpcoh_bfs configs/example/apu_se.py -n80 -u60 --cu-per-sa=60 --num-gpu-complex=1 --reg-alloc-policy=dynamic --barriers-per-cu=16 --num-tccs=8 --bw-scalor=8 --tcc-size=8192kB --tcc-assoc=32 --num-dirs=64 --mem-size=16GB --mem-type=HBM_1000_4H_1x64 --vreg-file-size=16384 --sreg-file-size=800 --num-hw-queues=256 --num-gpus=4 --gs-policy=GSP_RR --benchmark-root=multigpu_benchmarks/rodinia_host/bfs/ --coal-tokens=160 --gpu-clock=1801MHz --ruby-clock=1000MHz --TCC_latency=121 --vrf_lm_bus_latency=6 --mem-req-latency=69 --mem-resp-latency=69 --TCP_latency=16 --gs-num-sched-gpu=2 -c bfs --options="multigpu_benchmarks/rodinia_host/bfs/graph65536.txt" --max-coalesces-per-cycle=10 --sqc-size=16kB |& tee bfs_cpcoh.log  &

# BACKPROP
docker run --rm --volume $(pwd):$(pwd) -w $(pwd) cpcoh build/GCN3_X86/gem5.opt --debug-flags=GlobalScheduler,CPCoh,GPUDisp --debug-file=run_cpcoh.log --outdir=results_cpcoh_backprop configs/example/apu_se.py -n80 -u60 --cu-per-sa=60 --num-gpu-complex=1 --reg-alloc-policy=dynamic --barriers-per-cu=16 --num-tccs=8 --bw-scalor=8 --tcc-size=8192kB --tcc-assoc=32 --num-dirs=64 --mem-size=16GB --mem-type=HBM_1000_4H_1x64 --vreg-file-size=16384 --sreg-file-size=800 --num-hw-queues=256 --num-gpus=4 --gs-policy=GSP_RR --benchmark-root=multigpu_benchmarks/rodinia_host/backprop/ --coal-tokens=160 --gpu-clock=1801MHz --ruby-clock=1000MHz --TCC_latency=121 --vrf_lm_bus_latency=6 --mem-req-latency=69 --mem-resp-latency=69 --TCP_latency=16 --gs-num-sched-gpu=2 -c backprop --options="65536 1 1" --max-coalesces-per-cycle=10 --sqc-size=16kB |& tee backprop_cpcoh.log  &

# BTREE
docker run --rm --volume $(pwd):$(pwd) -w $(pwd) cpcoh build/GCN3_X86/gem5.opt --debug-flags=GlobalScheduler,CPCoh,GPUDisp --debug-file=run_cpcoh.log --outdir=results_cpcoh_btree configs/example/apu_se.py -n80 -u60 --cu-per-sa=60 --num-gpu-complex=1 --reg-alloc-policy=dynamic --barriers-per-cu=16 --num-tccs=8 --bw-scalor=8 --tcc-size=8192kB --tcc-assoc=32 --num-dirs=64 --mem-size=16GB --mem-type=HBM_1000_4H_1x64 --vreg-file-size=16384 --sreg-file-size=800 --num-hw-queues=256 --num-gpus=4 --gs-policy=GSP_RR --benchmark-root=multigpu_benchmarks/rodinia_host/b+tree/ --coal-tokens=160 --gpu-clock=1801MHz --ruby-clock=1000MHz --TCC_latency=121 --vrf_lm_bus_latency=6 --mem-req-latency=69 --mem-resp-latency=69 --TCP_latency=16 --gs-num-sched-gpu=2 -c b+tree.out --options="file multigpu_benchmarks/rodinia_host/b+tree/mil.txt command multigpu_benchmarks/rodinia_host/b+tree/command.txt" --max-coalesces-per-cycle=10 --sqc-size=16kB |& tee btree_cpcoh.log  &

# DWT2D
docker run --rm --volume $(pwd):$(pwd) -w $(pwd) cpcoh build/GCN3_X86/gem5.opt --debug-flags=GlobalScheduler,CPCoh,GPUDisp --debug-file=run_cpcoh.log --outdir=results_cpcoh_dwt2d configs/example/apu_se.py -n80 -u60 --cu-per-sa=60 --num-gpu-complex=1 --reg-alloc-policy=dynamic --barriers-per-cu=16 --num-tccs=8 --bw-scalor=8 --tcc-size=8192kB --tcc-assoc=32 --num-dirs=64 --mem-size=16GB --mem-type=HBM_1000_4H_1x64 --vreg-file-size=16384 --sreg-file-size=800 --num-hw-queues=256 --num-gpus=4 --gs-policy=GSP_RR --benchmark-root=multigpu_benchmarks/rodinia_host/dwt2d/ --coal-tokens=160 --gpu-clock=1801MHz --ruby-clock=1000MHz --TCC_latency=121 --vrf_lm_bus_latency=6 --mem-req-latency=69 --mem-resp-latency=69 --TCP_latency=16 --gs-num-sched-gpu=2 -c dwt2d --options="multigpu_benchmarks/rodinia_host/dwt2d/192.bmp -d 192x192 -f -5 -l 3 1 0" --max-coalesces-per-cycle=10 --sqc-size=16kB |& tee dwt2d_cpcoh.log  &

# GAUSSIAN
docker run --rm --volume $(pwd):$(pwd) -w $(pwd) cpcoh build/GCN3_X86/gem5.opt --debug-flags=GlobalScheduler,CPCoh,GPUDisp --debug-file=run_cpcoh.log --outdir=results_cpcoh_gaussian configs/exampgle/apu_se.py -n80 -u60 --cu-per-sa=60 --num-gpu-complex=1 --reg-alloc-policy=dynamic --barriers-per-cu=16 --num-tccs=8 --bw-scalor=8 --tcc-size=8192kB --tcc-assoc=32 --num-dirs=64 --mem-size=16GB --mem-type=HBM_1000_4H_1x64 --vreg-file-size=16384 --sreg-file-size=800 --num-hw-queues=256 --num-gpus=4 --gs-policy=GSP_RR --benchmark-root=multigpu_benchmarks/rodinia_host/gaussian/ --coal-tokens=160 --gpu-clock=1801MHz --ruby-clock=1000MHz --TCC_latency=121 --vrf_lm_bus_latency=6 --mem-req-latency=69 --mem-resp-latency=69 --TCP_latency=16 --gs-num-sched-gpu=2 -c gaussian --options="-f multigpu_benchmarks/rodinia_host/gaussian/matrix4.txt" --max-coalesces-per-cycle=10 --sqc-size=16kB |& tee gaussian_cpcoh.log  &

# HOTSPOT
docker run --rm --volume $(pwd):$(pwd) -w $(pwd) cpcoh build/GCN3_X86/gem5.opt --debug-flags=GlobalScheduler,CPCoh,GPUDisp --debug-file=run_cpcoh.log --outdir=results_cpcoh_hotspot configs/example/apu_se.py -n80 -u60 --cu-per-sa=60 --num-gpu-complex=1 --reg-alloc-policy=dynamic --barriers-per-cu=16 --num-tccs=8 --bw-scalor=8 --tcc-size=8192kB --tcc-assoc=32 --num-dirs=64 --mem-size=16GB --mem-type=HBM_1000_4H_1x64 --vreg-file-size=16384 --sreg-file-size=800 --num-hw-queues=256 --num-gpus=4 --gs-policy=GSP_RR --benchmark-root=multigpu_benchmarks/rodinia_host/hotspot/ --coal-tokens=160 --gpu-clock=1801MHz --ruby-clock=1000MHz --TCC_latency=121 --vrf_lm_bus_latency=6 --mem-req-latency=69 --mem-resp-latency=69 --TCP_latency=16 --gs-num-sched-gpu=2 -c hotspot --options="512 2 2 multigpu_benchmarks/rodinia_host/hotspot/temp_512 multigpu_benchmarks/rodinia_host/hotspot/power_512 multigpu_benchmarks/rodinia_host/hotspot/output.out" --max-coalesces-per-cycle=10 --sqc-size=16kB |& tee hotspot_cpcoh.log  &

# HUFFMAN
docker run --rm --volume $(pwd):$(pwd) -w $(pwd) cpcoh build/GCN3_X86/gem5.opt --debug-flags=GlobalScheduler,CPCoh,GPUDisp --debug-file=run_cpcoh.log --outdir=results_cpcoh_huffman configs/example/apu_se.py -n80 -u60 --cu-per-sa=60 --num-gpu-complex=1 --reg-alloc-policy=dynamic --barriers-per-cu=16 --num-tccs=8 --bw-scalor=8 --tcc-size=8192kB --tcc-assoc=32 --num-dirs=64 --mem-size=16GB --mem-type=HBM_1000_4H_1x64 --vreg-file-size=16384 --sreg-file-size=800 --num-hw-queues=256 --num-gpus=4 --gs-policy=GSP_RR --benchmark-root=multigpu_benchmarks/rodinia_host/huffman/ --coal-tokens=160 --gpu-clock=1801MHz --ruby-clock=1000MHz --TCC_latency=121 --vrf_lm_bus_latency=6 --mem-req-latency=69 --mem-resp-latency=69 --TCP_latency=16 --gs-num-sched-gpu=2 -c pavle --options="multigpu_benchmarks/rodinia_host/huffman/test1024_H2.206587175259.in 1 0" --max-coalesces-per-cycle=10 --sqc-size=16kB |& tee huffman_cpcoh.log  &

# LAVAMD
docker run --rm --volume $(pwd):$(pwd) -w $(pwd) cpcoh build/GCN3_X86/gem5.opt --debug-flags=GlobalScheduler,CPCoh,GPUDisp --debug-file=run_cpcoh.log --outdir=results_cpcoh_lavamd configs/example/apu_se.py -n80 -u60 --cu-per-sa=60 --num-gpu-complex=1 --reg-alloc-policy=dynamic --barriers-per-cu=16 --num-tccs=8 --bw-scalor=8 --tcc-size=8192kB --tcc-assoc=32 --num-dirs=64 --mem-size=16GB --mem-type=HBM_1000_4H_1x64 --vreg-file-size=16384 --sreg-file-size=800 --num-hw-queues=256 --num-gpus=4 --gs-policy=GSP_RR --benchmark-root=multigpu_benchmarks/rodinia_host/lavaMD/ --coal-tokens=160 --gpu-clock=1801MHz --ruby-clock=1000MHz --TCC_latency=121 --vrf_lm_bus_latency=6 --mem-req-latency=69 --mem-resp-latency=69 --TCP_latency=16 --gs-num-sched-gpu=2 -c lavaMD --options="-boxes1d 10" --max-coalesces-per-cycle=10 --sqc-size=16kB |& tee lavamd_cpcoh.log  &

# LUD
docker run --rm --volume $(pwd):$(pwd) -w $(pwd) cpcoh build/GCN3_X86/gem5.opt --debug-flags=GlobalScheduler,CPCoh,GPUDisp --debug-file=run_cpcoh.log --outdir=results_cpcoh_lud configs/example/apu_se.py -n80 -u60 --cu-per-sa=60 --num-gpu-complex=1 --reg-alloc-policy=dynamic --barriers-per-cu=16 --num-tccs=8 --bw-scalor=8 --tcc-size=8192kB --tcc-assoc=32 --num-dirs=64 --mem-size=16GB --mem-type=HBM_1000_4H_1x64 --vreg-file-size=16384 --sreg-file-size=800 --num-hw-queues=256 --num-gpus=4 --gs-policy=GSP_RR --benchmark-root=multigpu_benchmarks/rodinia_host/lud/hip/ --coal-tokens=160 --gpu-clock=1801MHz --ruby-clock=1000MHz --TCC_latency=121 --vrf_lm_bus_latency=6 --mem-req-latency=69 --mem-resp-latency=69 --TCP_latency=16 --gs-num-sched-gpu=2 -c lud_hip --options="-i multigpu_benchmarks/rodinia_host/lud/hip/256.dat" --max-coalesces-per-cycle=10 --sqc-size=16kB |& tee lud_cpcoh.log  &

docker run --rm --volume $(pwd):$(pwd) -w $(pwd) cpcoh build/GCN3_X86/gem5.opt --debug-flags=GlobalScheduler,CPCoh,GPUDisp --debug-file=run_cpcoh.log --outdir=results_cpcoh_nn configs/example/apu_se.py -n80 -u60 --cu-per-sa=60 --num-gpu-complex=1 --reg-alloc-policy=dynamic --barriers-per-cu=16 --num-tccs=8 --bw-scalor=8 --tcc-size=8192kB --tcc-assoc=32 --num-dirs=64 --mem-size=16GB --mem-type=HBM_1000_4H_1x64 --vreg-file-size=16384 --sreg-file-size=800 --num-hw-queues=256 --num-gpus=4 --gs-policy=GSP_RR --benchmark-root=multigpu_benchmarks/rodinia_host/nn/ --coal-tokens=160 --gpu-clock=1801MHz --ruby-clock=1000MHz --TCC_latency=121 --vrf_lm_bus_latency=6 --mem-req-latency=69 --mem-resp-latency=69 --TCP_latency=16 --gs-num-sched-gpu=2 -c nn --options="multigpu_benchmarks/rodinia_host/nn/filelist_4 -r 5 -lat 30 -lng 90" --max-coalesces-per-cycle=10 --sqc-size=16kB |& tee nn_cpcoh.log  &

docker run --rm --volume $(pwd):$(pwd) -w $(pwd) cpcoh build/GCN3_X86/gem5.opt --debug-flags=GlobalScheduler,CPCoh,GPUDisp --debug-file=run_cpcoh.log --outdir=results_cpcoh_nw configs/example/apu_se.py -n80 -u60 --cu-per-sa=60 --num-gpu-complex=1 --reg-alloc-policy=dynamic --barriers-per-cu=16 --num-tccs=8 --bw-scalor=8 --tcc-size=8192kB --tcc-assoc=32 --num-dirs=64 --mem-size=16GB --mem-type=HBM_1000_4H_1x64 --vreg-file-size=16384 --sreg-file-size=800 --num-hw-queues=256 --num-gpus=4 --gs-policy=GSP_RR --benchmark-root=multigpu_benchmarks/rodinia_host/nw/ --coal-tokens=160 --gpu-clock=1801MHz --ruby-clock=1000MHz --TCC_latency=121 --vrf_lm_bus_latency=6 --mem-req-latency=69 --mem-resp-latency=69 --TCP_latency=16 --gs-num-sched-gpu=2 -c needle --options="2048 10" --max-coalesces-per-cycle=10 --sqc-size=16kB |& tee nw_cpcoh.log  &

# PATHFINDER
docker run --rm --volume $(pwd):$(pwd) -w $(pwd) cpcoh build/GCN3_X86/gem5.opt --debug-flags=GlobalScheduler,CPCoh,GPUDisp --debug-file=run_cpcoh.log --outdir=results_cpcoh_pathfinder configs/example/apu_se.py -n80 -u60 --cu-per-sa=60 --num-gpu-complex=1 --reg-alloc-policy=dynamic --barriers-per-cu=16 --num-tccs=8 --bw-scalor=8 --tcc-size=8192kB --tcc-assoc=32 --num-dirs=64 --mem-size=16GB --mem-type=HBM_1000_4H_1x64 --vreg-file-size=16384 --sreg-file-size=800 --num-hw-queues=256 --num-gpus=4 --gs-policy=GSP_RR --benchmark-root=multigpu_benchmarks/rodinia_host/pathfinder/ --coal-tokens=160 --gpu-clock=1801MHz --ruby-clock=1000MHz --TCC_latency=121 --vrf_lm_bus_latency=6 --mem-req-latency=69 --mem-resp-latency=69 --TCP_latency=16 --gs-num-sched-gpu=2 -c pathfinder --options="100000 100 20" --max-coalesces-per-cycle=10 --sqc-size=16kB |& tee pathfinder_cpcoh.log  &

# STREAM CLUSTER
docker run --rm --volume $(pwd):$(pwd) -w $(pwd) cpcoh build/GCN3_X86/gem5.opt --debug-flags=GlobalScheduler,CPCoh,GPUDisp --debug-file=run_cpcoh.log --outdir=results_cpcoh_streamcluster configs/example/apu_se.py -n80 -u60 --cu-per-sa=60 --num-gpu-complex=1 --reg-alloc-policy=dynamic --barriers-per-cu=16 --num-tccs=8 --bw-scalor=8 --tcc-size=8192kB --tcc-assoc=32 --num-dirs=64 --mem-size=16GB --mem-type=HBM_1000_4H_1x64 --vreg-file-size=16384 --sreg-file-size=800 --num-hw-queues=256 --num-gpus=4 --gs-policy=GSP_RR --benchmark-root=multigpu_benchmarks/rodinia_host/streamcluster/ --coal-tokens=160 --gpu-clock=1801MHz --ruby-clock=1000MHz --TCC_latency=121 --vrf_lm_bus_latency=6 --mem-req-latency=69 --mem-resp-latency=69 --TCP_latency=16 --gs-num-sched-gpu=2 -c sc_gpu --options="10 20 256 65536 65536 1000 none output.txt 1" --max-coalesces-per-cycle=10 --sqc-size=16kB |& tee streamcluster_cpcoh.log  &

# SRAD v2
docker run --rm --volume $(pwd):$(pwd) -w $(pwd) cpcoh build/GCN3_X86/gem5.opt --debug-flags=GlobalScheduler,CPCoh,GPUDisp --debug-file=run_cpcoh.log --outdir=results_cpcoh_srad_v2 configs/example/apu_se.py -n80 -u60 --cu-per-sa=60 --num-gpu-complex=1 --reg-alloc-policy=dynamic --barriers-per-cu=16 --num-tccs=8 --bw-scalor=8 --tcc-size=8192kB --tcc-assoc=32 --num-dirs=64 --mem-size=16GB --mem-type=HBM_1000_4H_1x64 --vreg-file-size=16384 --sreg-file-size=800 --num-hw-queues=256 --num-gpus=4 --gs-policy=GSP_RR --benchmark-root=multigpu_benchmarks/rodinia_host/srad/srad_v2/ --coal-tokens=160 --gpu-clock=1801MHz --ruby-clock=1000MHz --TCC_latency=121 --vrf_lm_bus_latency=6 --mem-req-latency=69 --mem-resp-latency=69 --TCP_latency=16 --gs-num-sched-gpu=2 -c srad --options="2048 2048 0 127 0 127 0.5 2" --max-coalesces-per-cycle=10 --sqc-size=16kB |& tee srad_v2_cpcoh.log  &


# SRAD v1
docker run --rm --volume $(pwd):$(pwd) -w $(pwd) cpcoh build/GCN3_X86/gem5.opt --debug-flags=GlobalScheduler,CPCoh,GPUDisp --debug-file=run_cpcoh.log --outdir=results_cpcoh_srad_v1 configs/example/apu_se.py -n80 -u60 --cu-per-sa=60 --num-gpu-complex=1 --reg-alloc-policy=dynamic --barriers-per-cu=16 --num-tccs=8 --bw-scalor=8 --tcc-size=8192kB --tcc-assoc=32 --num-dirs=64 --mem-size=16GB --mem-type=HBM_1000_4H_1x64 --vreg-file-size=16384 --sreg-file-size=800 --num-hw-queues=256 --num-gpus=4 --gs-policy=GSP_RR --benchmark-root=multigpu_benchmarks/rodinia_host/srad/srad_v1/ --coal-tokens=160 --gpu-clock=1801MHz --ruby-clock=1000MHz --TCC_latency=121 --vrf_lm_bus_latency=6 --mem-req-latency=69 --mem-resp-latency=69 --TCP_latency=16 --gs-num-sched-gpu=2 -c srad_v1 --options="100 0.5 502 458" --max-coalesces-per-cycle=10 --sqc-size=16kB |& tee srad_v1_cpcoh.log  &